### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by antonymarion** [Hippogriff/3DCSGNet#1]
Hi,

I am getting a KeyError: 'p(48,32,32,8,12)'
I tried to change the length and expression=None but it did not solve the issue.

Any clue?
Regards,

**Comment by Hippogriff** [comment]
Where exactly are you getting this error? Please post the line number and also which script are you running? More details the better.

**Comment by Hippogriff** [comment]
Oh I see! It seems that particular primitive is not pre-rendered. You can try some other primitive, like sp(16,40,16,12), instead of sp(48,32,32,8,12).

**Comment by antonymarion** [comment]
Thank you for your answer.
