### ISSUE TITLE
Dimensions of cube voxel off by 1

### ISSUE THREAD

**Issue by croros** [Hippogriff/3DCSGNet#2]
For example, for the cube 'cu(16,16,16,8)', the output voxel (in both the .h5 and the draw_cube function) is 7 by 7 by 7, not 8 by 8 by 8. 
Upon further inspection, draw_cube only gives the true dimensions for a cube if the side length is odd, presumably because only odd-sided cubes can have a true center in voxel space (but technically speaking even-sided cubes can be made). Was this intentional? Any suggestions for fixing this? 

Thanks

**Comment by Hippogriff** [comment]
This was not intentional. This was more like an indexing error that I realized much later. Since I have cached primitives in .h5 format (for efficiency), unfortunately there is no easy hack. You will have to recreate the dataset, which I guess will be too much trouble. Sorry.
