### ISSUE TITLE
visualize the result

### ISSUE THREAD

**Issue by Enigma-li** [Hippogriff/3DCSGNet#5]
Hi,

After running the test.py with the pretrained model, I got some output with three files:
pred.txt  results.org  target.txt

Is there a way to visualize the results, e.g., in voxel format?

**Comment by Hippogriff** [comment]
You can use the procedure mentioned in the README.md (note that each line in the pred.txt is a program, so you can fill the `expressions` variable below with those programs and get the voxels):

```
import deepdish as dd
from src.Utils.train_utils import voxels_from_expressions

# pre-rendered shape primitives in the form of voxels for better performance
primitives = dd.io.load("data/primitives.h5")
expressions = ["cy(48,48,32,8,12)cu(24,24,40,28)+", "sp(48,32,32,8,12)cu(24,24,40,28)+"]

voxels = voxels_from_expressions(expressions, primitives, max_len=7)
print(voxels.shape)

(2, 64, 64, 64)
```
